# ========================================
# hugo-simple ä¸»é¢˜èœå•é…ç½®
# ========================================

[[main]]
  identifier = "categories"
  name = "åˆ†ç±»"
  url = "#"
  weight = 2

  # åˆ†ç±»å­èœå•
  [[main]]
    name = "ğŸ–¥ï¸ è¿ç»´"
    parent = "categories"
    url = "/linux/"
    weight = 1

  [[main]]
    name = "ğŸ¨ å‰ç«¯"
    parent = "categories"
    url = "/frontend/"
    weight = 2

  [[main]]
    name = "ğŸ’» ç¼–ç¨‹"
    parent = "categories"
    url = "/code/"
    weight = 3

  [[main]]
    name = "ğŸ” é»‘å®¢"
    parent = "categories"
    url = "/hacker/"
    weight = 4

  [[main]]
    name = "ğŸ› ï¸ ä¸“é¢˜"
    parent = "categories"
    url = "/topic/"
    weight = 5

[[main]]
  name = "å¥½å‹"
  url = "/friends/"
  weight = 3

[[main]]
  name = "å…³äº"
  url = "/about/"
  weight = 4

[[main]]
  name = "å½’æ¡£"
  url = "/archives/"
  weight = 5
